GoldenNaina/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('customers/', include('Customers.urls')),
    path('orders/', include('orders.urls')),
    path('home/', include('HomeApp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from paypal.standard.ipn import urls as paypal_urls

urlpatterns =[
    # cart

    path('cart', views.show_cart, name='cart'),
    path('add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('remove_item/<int:pk>', views.remove_item_from_cart, name='remove_item'),

    path('checkout', views.checkout_process, name='checkout'),
    
    path('coupons', views.Coupons_view, name='coupons'),
    
    # payment

    path('process_payment/', views.process_payment, name='process_payment'),
    path('payment_success/<int:address_id>/<int:order_id>/', views.payment_success, name='payment_success'),
    path('payment-failed/', views.payment_failed_view, name='payment-failed'),

    # orders

    path('orders/', views.show_orders, name='orders'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('orders/cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),

    # returns and refunds

    path('orders/return/<int:order_id>/', views.request_return, name='return_order'),
    path('orders/refund/<int:order_id>/', views.request_refund, name='request_refund'),
    path('refund_approved/', views.refund_approved, name='refund_approved'),

]

Customers/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    LIVE = 1
    DELETE = 0
    DELETE_CHOICES = ((LIVE, 'Live'), (DELETE, 'Delete'))

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer_profile')

    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    delete_status = models.IntegerField(choices=DELETE_CHOICES, default=LIVE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Customer_Address(models.Model):
    name = models.CharField(max_length=255)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='addresses')
    street_address = models.CharField(max_length=255)  # P.O Box
    city = models.CharField(max_length=100, default='AbuDubai')  # Default to Dubai
    emirates = models.CharField(max_length=100, default='AbuDubai')  # Default to Dubai
    zip_code = models.CharField(max_length=20)  # Zip code
    country = models.CharField(max_length=100, default='United Arab Emirates')  
    mobile_number = models.CharField(max_length=20)  # 971-(1)968565699
    address_type = models.CharField(max_length=10, choices=(('Home', 'Home'), ('Work', 'Work')), default='Home')

    def __str__(self):
        return f"{self.street_address}, {self.city}, {self.emirates}, {self.zip_code}, {self.country}, {self.address_type}, {self.mobile_number}, {self.name}"

    

class ContactUs(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    class Meta:
        verbose_name = 'Contact Us'
        verbose_name_plural = 'Contact Us'
    
    def __str__(self) -> str:
        return self.full_name
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    full_name = models.CharField(max_length=100)
    bio = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='profiles/', null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    verified = models.BooleanField(default=True)

    def __str__(self):
        return self.full_name

orders/models.py
from django.db import models
from Customers.models import Customer, Customer_Address
from products.models import Product, ProductImages, Stock, Size
from django.contrib import admin  
from django.utils import timezone
from django.core.exceptions import ValidationError
from datetime import timedelta


class Order(models.Model):
    LIVE = 1
    DELETE = 0
    DELETE_CHOICES = ((LIVE, 'Live'), (DELETE, 'Delete'))
    CART_STAGE = 0
    ORDER_CONFIRM = 1
    ORDER_PROCESSED = 2
    ORDER_DELIVERED = 3
    ORDER_REJECTED = 4
    ORDER_CANCELLED = 5
    STATUS_CHOICES = (
        (ORDER_CONFIRM, 'ORDER_CONFIRM'),
        (ORDER_PROCESSED, 'ORDER_PROCESSED'),
        (ORDER_DELIVERED, "ORDER_DELIVERED"),
        (ORDER_CANCELLED, "ORDER_CANCELLED")
    )
    RETURN_REQUESTED = 'requested'
    RETURN_APPROVED = 'approved'
    RETURN_DECLINED = 'declined'
    REFUND_INITIATED = 'Refund Initiated'
    REFUND_COMPLETED = 'Refund completed'
    RETURN_STATUS_CHOICES = [
        (RETURN_REQUESTED, 'Return Requested'),
        (RETURN_APPROVED, 'Return Approved'),
        (RETURN_DECLINED, 'Return Declined'),
        (REFUND_INITIATED, 'Refund Initiated'),
        (REFUND_COMPLETED , 'Refund completed'),
    ]
    order_status = models.IntegerField(choices=STATUS_CHOICES, default=CART_STAGE)
    owner = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, related_name='orders')
    delete_status = models.IntegerField(choices=DELETE_CHOICES, default=LIVE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    coupons = models.ManyToManyField('Coupon', blank=True)
    total_price = models.FloatField(default=0.00)
    address = models.ForeignKey(Customer_Address, on_delete=models.SET_NULL, null=True, related_name='orders')
    return_status = models.CharField(
        max_length=20,
        choices=RETURN_STATUS_CHOICES,
        default=None,
        blank=True,
        null=True
    )
    is_refund_requested = models.BooleanField(default=False)
    is_returned = models.BooleanField(default=False)
    is_refund_paid = models.BooleanField(default=False)
    return_reason = models.TextField(null=True, blank=True)
    return_request_date = models.DateTimeField(default=timezone.now, null=True, blank=True)
    bank_name = models.CharField(max_length=255, null=True, blank=True)
    account_number = models.CharField(max_length=255, null=True, blank=True)
    ifsc_code = models.CharField(max_length=255, null=True, blank=True)
    payment_method = models.CharField(max_length=20, choices=[('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], default='paypal')

    def cancel_order(self):
        self.order_status = self.ORDER_CANCELLED
        self.save()

    def decrease_stock(self):
        for item in self.added_items.all():
            try:
                size_obj = Size.objects.get(name=item.size)
                print(f"Trying to decrease stock for Product: {item.product}, Size: {size_obj.name}, Quantity: {item.quantity}")
                
                stock_item = Stock.objects.get(product=item.product, size=size_obj)
                print(f"Current stock quantity for Product: {item.product}, Size: {size_obj.name} is {stock_item.quantity}")
                
                stock_item.quantity -= item.quantity
                stock_item.save()

                print(f"Stock decreased for Product: {item.product}, Size: {size_obj.name}, New Quantity: {stock_item.quantity}")
                
            except Size.DoesNotExist:
                print(f"Size {item.size} does not exist")
            except Stock.DoesNotExist:
                print(f"Stock item does not exist for Product: {item.product}, Size: {item.size}")
            except Exception as e:
                print(f"Error updating stock: {e}")

    def is_within_return_period(self):
        for item in self.added_items.all():
            return_policy_days = item.get_return_policy_days()
            if (timezone.now() - self.created_at) > timedelta(days=return_policy_days):
                return False
        return True




class OrderedItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='added_items')
    owner = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='added_items')
    quantity = models.PositiveIntegerField()
    size = models.CharField(max_length=5, choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small'), ('XXL', 'Extra Extra Large'), ('XL', 'Extra Large')], null=True) 
    is_returned = models.BooleanField(default=False)
    return_request_date = models.DateTimeField(null=True, blank=True)
    return_approved_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.product.title} ( {self.size} ) x {self.quantity}"

    @property
    def product_price(self):
        return self.product.discount_price if self.product else 'No product'

    @admin.display(description='Product Price')
    def product_price_display(self):
        return self.product_price

    def get_return_policy_days(self):
        # Fetch the return policy days from the associated product
        return int(self.product.return_policy)

    

class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount = models.FloatField(help_text='Percentage discount')
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    active = models.BooleanField(default=False)
    description = models.TextField(blank=True, help_text='Description of the coupon')
    terms_and_conditions = models.TextField(blank=True, help_text='Terms and conditions of the coupon', null=True)

    def __str__(self):
        return self.code

class Cart_Offers(models.Model):
    offer_id = models.CharField(max_length=100)
    offer_name = models.CharField(max_length=200)
    offer_description = models.TextField()

    def __str__(self):
        return self.offer_name

class Payment(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='payments')
    order = models.OneToOneField(Order, on_delete=models.CASCADE, related_name='payment')
    razorpay_order_id = models.CharField(max_length=100, blank=True, null=True)
    razorpay_payment_id = models.CharField(max_length=100, blank=True, null=True)
    razorpay_payment_status = models.CharField(max_length=100, blank=True, null=True)
    payment_method = models.CharField(max_length=20, choices=[('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], default='paypal')
    paid = models.BooleanField(default=False)
    amount = models.FloatField(default=0.00)
    status = models.CharField(max_length=20, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f"{self.user.name} - {self.order.id}"

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models import Avg
from django.core.exceptions import ValidationError
from django.urls import reverse




RATING = (
    (1, '🌟'),
    (2, '🌟🌟'),
    (3, '🌟🌟🌟'),
    (4, '🌟🌟🌟🌟'),
    (5, '🌟🌟🌟🌟🌟')
)



class Size(models.Model):
    name = models.CharField(max_length=3, unique=True)

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='categories', null=True)
    percentage = models.IntegerField(default=0, null=True) # remove null later


    def __str__(self):
        return self.name

class Product(models.Model):
    LIVE = 1
    DELETE = 0
    DELETE_CHOICES = ((LIVE, 'Live'), (DELETE, 'Delete'))

    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    image = models.ImageField(upload_to='media/')
    priority = models.IntegerField(default=0)
    delete_status = models.IntegerField(choices=DELETE_CHOICES, default=LIVE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    rating = models.IntegerField(default=5)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    return_policy = models.TextField(blank=True, null=True, help_text='Return policy in days', default='7')

    class Meta:
        ordering = ['-priority', '-created_at']

    def __str__(self):
        return self.title

    def clean(self):
        if self.discount_price and self.discount_price > self.price:
            raise ValidationError("Discount price should not be greater than the price")

    def get_percentage(self):
        if self.discount_price:
            return int(((self.price - self.discount_price) / self.price) * 100)
        return 0

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def get_rating_stars(self):
        return '⭐' * self.rating

    def get_average_rating(self):
        avg_rating = self.reviews.aggregate(average=Avg('rating'))['average']
        return avg_rating if avg_rating else 5

    def get_average_rating_stars(self):
        return '⭐' * round(self.get_average_rating())

    def get_stock_for_size(self, size):
        try:
            stock = self.stocks.get(size=size)
            return stock.quantity
        except Stock.DoesNotExist:
            return 0


class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='stocks')
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.product.title} - {self.size.name}: {self.quantity}"


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name='product_images', null=True)
    images = models.ImageField(upload_to='product_images', null=True)

    class Meta:
        ordering = ['-id']

class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING, default=None)
    review = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Product Reviews'
  
    def __str__(self):
        return f"{self.user.username} - {self.product.title}"

    def get_rating(self):
        return self.rating

class Wishlist(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='wishlist_items')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Wishlists'

    def __str__(self):
        return self.product.title if self.product else 'No Product'

class Theme_model(models.Model):
    image = models.ImageField(upload_to='theme_models')
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)


class PopularSearch(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255, help_text="Enter the URL or name of the view to link to")

    def __str__(self):
        return self.name

    def get_url(self):
        try:
            return reverse(self.url)
        except:
            return self.url  # Return the URL as is if it's not a view name

orders/forms.py
from django import forms
from Customers.models import Customer_Address



class AddressForm(forms.ModelForm):
    class Meta:
        model = Customer_Address
        fields = [
            'name', 
            'street_address', 
            'city', 
            'emirates', 
            'zip_code', 
            'country', 
            'address_type', 
            'mobile_number'
        ]

templates/account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Golden Naina</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    *{
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    
    body {
        font-family: 'Poppins', sans-serif;
        background-image: url('{% static "images/login-hero-banner.jpg" %}');
        background-size: cover; 
        background-repeat: no-repeat;
        height: 100vh;
    }
    
    
    
    a{
        text-decoration: none;
        color: #555;
    }
    
    .container{
        max-width: 1300px;
        margin: auto;
        padding-left: 25px;
        padding-right: 25px;
    }
    .row{
        display: flex;
        align-items: center;
        flex-wrap: wrap;
        justify-content: space-around;
    }
    .col-2{
        flex-basis: 50%;
        min-width: 300px;
    }
    .col-2 img{
        max-width: 100%;
        padding: 50px 0;
    }
    .col-2 h1{
        font-size: 50px;
        line-height: 60px;
        margin: 25px 0;
    }
    .btn{
        display: inline-block;
        background: #000;
        color: gold;
        padding: 8px 30px;
        margin: 30px 0;
        border-radius: 30px;
        transition: background 0.5s;
    }
    .btn:hover{
        background: #000;
    }

 
   
    
    /* Account page */
    .account-page{
        padding: 50px 0;
        width: 100%;
        border: none;
        outline: none;
        height: 100%;
    }
    .form-container{
        
        background: #fff;
        width: 300px;
        height: 400px;
        position: relative;
        text-align: center;
        padding: 20px 0;
        margin: auto;
        box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.1);
        overflow: hidden;
    }
    .form-container span{
        font-weight: bold;
        padding: 0 10px;
        color: #555;
        cursor: pointer;
        width: 100px;
        display: inline-block;
    }
    .form-btn{
        display: inline-block;
    }
    .form-container form{
        max-width: 300px;
        padding: 0 20px;
        position: absolute;
        top: 130px;
        transition: transform 1s;
    }
    form input{
        width: 100%;
        height: 30px;
        margin: 10px 0;
        padding: 0 10px;
        border: 1px solid #ccc;
    }
    form .btn{
        width: 100%;
        border: none;
        cursor: pointer;
        margin: 10px 0;
    }
    form .btn:focus{
        outline: none;
    }
    #LoginForm{
        left: -300px;
    }
    #RegForm{
        left: 0;
    }
    form a{
        font-size: 12px;
    }
    #Indicator{
        width: 100px;
        border: none;
        background: #000;
        height: 3px;
        margin-top: 8px;
        transform: translateX(100px);
        transition: transform 2s;
    }
    
   
</style>
</head>

<body>
    <div class="account-page">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="form-container">
                        <div class="form-btn">
                            <span onclick="login()">Login</span>
                            <span onclick="register()">Register</span>
                            <hr id="Indicator">
                        </div>
                        <form id="LoginForm" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="text" name="username" required placeholder="Username">
                            <input type="password" name="password" required placeholder="Password">
                            <button type="submit" name="login" class="btn">Login</button>
                            <a href="{% url 'password_reset' %}
                            ">Forget Password</a>
                        </form>
                        <form id="RegForm" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="text" name="username" required maxlength="14" minlength="4" placeholder="Username">
                            <input type="email" name="email" required placeholder="Email">
                            <input type="password" name="password" required minlength="6" placeholder="Password">
                            <button type="submit" name="register" class="btn">Register</button>
                        </form>
                        {% if error %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        var LoginForm = document.getElementById("LoginForm");
        var RegForm = document.getElementById("RegForm");
        var Indicator = document.getElementById("Indicator");
        function register() {
            RegForm.style.transform = "translateX(0px)";
            LoginForm.style.transform = "translateX(0px)";
            Indicator.style.transform = "translateX(100px)";
        }
        function login() {
            RegForm.style.transform = "translateX(300px)";
            LoginForm.style.transform = "translateX(300px)";
            Indicator.style.transform = "translateX(0px)";
        }
        
    </script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.3/js/bootstrap.bundle.min.js" integrity="sha384-xxxxx" crossorigin="anonymous"></script>
    {% if register %}
    <script>
        register()
    </script>
    {% else %}
    <script>
        login()
    </script>
    {% endif %}
    

</body>

</html>
  
     
 

 

templates/category_detail.html
{% extends 'partials/base.html' %}

{% block title %}{{ category.name }}{% endblock %}
{% load static %}

{% block content %}
<section class="section category-detail main-content">
    <section class="sorting">
        <form method="get" class="filter-control">
            <select id="sort" name="sort" onchange="this.form.submit()">
                <option value="default" {% if sort_option == 'default' %}selected{% endif %}>Sort</option>
                <option value="low_to_high" {% if sort_option == 'low_to_high' %}selected{% endif %}>Price: Low to High</option>
                <option value="high_to_low" {% if sort_option == 'high_to_low' %}selected{% endif %}>Price: High to Low</option>
            </select>
        </form>
    </section>
    <div class="container">
    <div class="row">
                <div class="products">
                    {% for product in products %}
                    <div class="product-list">
                        <span class="discount-label">{{ product.get_percentage }}% OFF</span>
                        <a href="{% url 'product_detail' product.pk %}">
                            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.title }}">
                        </a>
                        <div class="rating">
                            {% for i in ''|ljust:product.rating %}
                                ★
                            {% endfor %}
                        </div>
                        <div class="card-body">
                            <h5 class="brand">{{ product.title }}</h5>
                            <p class="description">{{ product.description|truncatewords:20 }}</p>
                            <p class="price"><span class="old-price">AED {{ product.price }}</span> AED {{ product.discount_price }}</p>
                            <a href="{% url 'product_detail' product.pk %}" class="btn btn-primary">View Product</a>
                            <div class="wishlist-icon"></div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="?page={{ products.previous_page_number }}&sort={{ sort_option }}">Previous</a>
                    {% endif %}

                    {% for i in products.paginator.page_range %}
                        <a href="?page={{ i }}&sort={{ sort_option }}" {% if products.number == i %}class="active"{% endif %}>{{ i }}</a>
                    {% endfor %}

                    {% if products.has_next %}
                        <a href="?page={{ products.next_page_number }}&sort={{ sort_option }}">Next</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/contact_success.html
{% extends "partials/base.html" %}
{% load static %}

{% block content %}
  <div class="contact-success-container">
    <img src="{% static 'images/checkmark.webp' %}" alt="Success" class="contact-success-checkmark">
    <h1>Thank you! Your message has been sent successfully.</h1>
    <a href="{% url 'Products' %}" class="contact-success-home-link">Return to Home</a>
  </div>
{% endblock %}

templates/customer_dashboard.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<main class="dashboard">
  <div class="profile">
    {% if profile.image %}
      <img src="{{ profile.image.url }}" alt="Profile Picture">
    {% else %}
    <img src="{% static 'images/profile-userprofile.jpeg' %}" alt="Profile Picture">
    {% endif %}
    <p>{{ profile.full_name }} {% if profile.verified %}
      <p class="text-success"><i class="fa fa-check-circle" aria-hidden="true"></i> Verified</p>
      {% else %}
      <p class="text-danger"><i class="fa fa-times-circle" aria-hidden="true"></i> Not Verified</p>
      {% endif %}</p>
  </div>
  <div class="cards">
      <section class="card">
          <a href="{% url 'orders' %}">
              <h2>Orders <span class="arrow">→</span></h2>
          </a>
          <p>Check your order status</p>
      </section>
      <section class="card">
          <a href="{% url 'wishlist_view' %}">
              <h2>Wishlist <span class="arrow">→</span></h2>
          </a>
          <p>All your curated product collections</p>
      </section>
      <section class="card">
          <a href="{% url 'address_list' %}">
              <h2>Addresses <span class="arrow">→</span></h2>
          </a>
          <p>Save addresses for a hassle-free checkout</p>
      </section>
      <section class="card">
          <a href="{% url 'coupons' %}">
              <h2>Coupons <span class="arrow">→</span></h2>
          </a>
          <p>Manage coupons for additional discounts</p>
      </section>
      <section class="card">
          <a href="{% url 'edit_profile' %}">
              <h2>Profile<span class="arrow">→</span></h2>
          </a>
          <p>Change your profile details</p>
      </section>
      <section class="card">
        <a href="{% url 'Logout' %}">
            <h2>Logout <span class="arrow">→</span></h2>
        </a>
        <p>Logout your Account</p>
    </section>
  </div>
</main>

{% endblock %}

{% block scripts %}
<script>
  document.querySelectorAll('.card').forEach(card => {
      card.addEventListener('click', () => {
          card.classList.toggle('active');
      });
  });
</script>
{% endblock %}

templates/offer_themes.html
{% extends 'partials/base.html' %}

{% block content %}
{% load static %}

<div class="offer-themes-container">

    <div class="small-container">
      <section class="hero" id="home" style="background-image: url('{{ theme.image.url }}');">
          <div class="container">
              <div class="hero-content">
                  <p class="hero-subtitle">{{ theme.title }}</p>
                  <h2 class="h1 hero-title">{{ theme.description }}</h2>
                  <button class="btn btn-primary">Shop Now</button>
              </div>
          </div>
      </section>
  </div>
    
</div>

<style>
.offer-themes-container {
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    background-color: #f7f7f7;
}

.hero {
    width: 100%;
    height: 100vh;
    background-size: cover;
    background-position: center;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 20px;
}

.hero-content {
    text-align: center;
    color: white;
    background: rgba(0, 0, 0, 0.5);
    padding: 20px;
    border-radius: 10px;
}

.hero-subtitle {
    font-size: 1.5rem;
    margin-bottom: 10px;
}

.hero-title {
    font-size: 2.5rem;
    margin-bottom: 20px;
}

.btn-primary {
    padding: 10px 20px;
    font-size: 1rem;
    color: white;
    background-color: #007bff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

.btn-primary:hover {
    background-color: #0056b3;
}
</style>

{% endblock %}

templates/profile_update.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<div class="dashboard-container">
    
    <div class="dashboard-content">
        <span>
            {% if profile.image %}
            <img src="{{ profile.image.url }}" class="profile-image">
            {% else %}
            <img src="{% static 'images/profile-userprofile.jpeg' %}" class="profile-image" alt="Default Profile Image">
            {% endif %}
        </span>
        <form method="post" enctype="multipart/form-data" class="profile-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_full_name">Full Name:</label>
                {{ form.full_name }}
            </div>
            <div class="form-group">
                <label for="id_bio">Bio:</label>
                {{ form.bio }}
            </div>
            <div class="form-group">
                <label for="id_phone">Phone:</label>
                {{ form.phone }}
            </div>
            <div class="form-group">
                <label for="id_image">Profile Image:</label>
                {{ form.image }}
            </div>
            <button type="submit" class="update-button">Update Profile</button>
        </form>
        <div class="verification-status">
            {% if profile.verified %}
            <span class="verified">Verified<i class="fa fa-check" aria-hidden="true"></i></span>
            {% else %}
            <span class="not-verified">Not Verified<i class="fa fa-times" aria-hidden="true"></i></span>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}